// <auto-generated />
namespace Server.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ActorDbAddFirstandLastName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ActorDbAddFirstandLastName));
        
        string IMigrationMetadata.Id
        {
            get { return "202207281057476_ActorDb Add First and Last Name"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
