// <auto-generated />
namespace Server.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addroomIdtoSession : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addroomIdtoSession));
        
        string IMigrationMetadata.Id
        {
            get { return "202207281158510_add roomId to Session "; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
