// <auto-generated />
namespace Server.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class add2tablesRoomSeatDbandRoomTypeDb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add2tablesRoomSeatDbandRoomTypeDb));
        
        string IMigrationMetadata.Id
        {
            get { return "202207281225037_add 2 tables(RoomSeatDb and RoomTypeDb)"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
